# -*- coding: utf-8 -*-
"""Enfield.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvZ6Y3AAoA9YBOKN4WWWDrq1R1i0sflc
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

df=pd.read_excel("/content/royalenfield.xlsx")

df

df=df.rename(columns={"Date":'ds',"Sales":'y'})

df

def remove_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.28)
    Q3 = df[column].quantile(0.78)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]
df1=remove_outliers_iqr(df,'y')

df1

from prophet import Prophet

model=Prophet()

model.fit(df1)

future=model.make_future_dataframe(periods=12, freq='M')

forecast=model.predict(future)

forecast

y_pred=forecast['yhat'][:len(df1)]

y_true=df1['y']

from sklearn.metrics import r2_score

r2_score(y_true,y_pred)

from prophet.plot import plot_plotly,plot_components_plotly

plot_plotly(model,forecast)

plot_components_plotly(model,forecast)

from prophet.diagnostics import cross_validation,performance_metrics

df_cv=cross_validation(model,initial='730 days',period='90 days',horizon='30 days')
df_p=performance_metrics(df_cv)

df_p





